import mongoose from "mongoose";

const todoSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true
  },

  title: {
    type: String,
    required: true,
    trim: true
  },

  description: {
    type: String,
    trim: true
  },

  dueDate: {
    type: Date,
    required: true
  },

  priority: {
    type: String,
    enum: ["Low", "Medium", "High"],
    default: "Medium"
  },

  isComplete: {
    type: Boolean,
    default: false
  },

  aiSummary: {
    type: String,  // summary generated by AI (Task 3)
    default: ""
  }

}, { timestamps: true }); 
const TodoModel = mongoose.model('todo', todoSchema);
export default TodoModel;
